/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EducationRouteImport } from './routes/education'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PersonalInfoRouteImport } from './routes/personal-info'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as SubmitApplicationRouteImport } from './routes/submit-application'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInfoRoute = PersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitApplicationRoute = SubmitApplicationRouteImport.update({
  id: '/submit-application',
  path: '/submit-application',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/personal-info': typeof PersonalInfoRoute
  '/programmes': typeof ProgrammesRoute
  '/registration': typeof RegistrationRoute
  '/study-plan': typeof StudyPlanRoute
  '/submit-application': typeof SubmitApplicationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/personal-info': typeof PersonalInfoRoute
  '/programmes': typeof ProgrammesRoute
  '/registration': typeof RegistrationRoute
  '/study-plan': typeof StudyPlanRoute
  '/submit-application': typeof SubmitApplicationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/personal-info': typeof PersonalInfoRoute
  '/programmes': typeof ProgrammesRoute
  '/registration': typeof RegistrationRoute
  '/study-plan': typeof StudyPlanRoute
  '/submit-application': typeof SubmitApplicationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/education'
    | '/login'
    | '/payments'
    | '/personal-info'
    | '/programmes'
    | '/registration'
    | '/study-plan'
    | '/submit-application'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/education'
    | '/login'
    | '/payments'
    | '/personal-info'
    | '/programmes'
    | '/registration'
    | '/study-plan'
    | '/submit-application'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/education'
    | '/login'
    | '/payments'
    | '/personal-info'
    | '/programmes'
    | '/registration'
    | '/study-plan'
    | '/submit-application'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  EducationRoute: typeof EducationRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  PersonalInfoRoute: typeof PersonalInfoRoute
  ProgrammesRoute: typeof ProgrammesRoute
  RegistrationRoute: typeof RegistrationRoute
  StudyPlanRoute: typeof StudyPlanRoute
  SubmitApplicationRoute: typeof SubmitApplicationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-info': {
      id: '/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof PersonalInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-application': {
      id: '/submit-application'
      path: '/submit-application'
      fullPath: '/submit-application'
      preLoaderRoute: typeof SubmitApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  EducationRoute: EducationRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  PersonalInfoRoute: PersonalInfoRoute,
  ProgrammesRoute: ProgrammesRoute,
  RegistrationRoute: RegistrationRoute,
  StudyPlanRoute: StudyPlanRoute,
  SubmitApplicationRoute: SubmitApplicationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
