/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicantRouteRouteImport } from './routes/_applicant/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficerRouteRouteImport } from './routes/officer/route'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ApplicantCoursesRouteImport } from './routes/_applicant/courses'
import { Route as ApplicantDashboardRouteImport } from './routes/_applicant/dashboard'
import { Route as ApplicantEducationRouteImport } from './routes/_applicant/education'
import { Route as ApplicantPaymentsRouteImport } from './routes/_applicant/payments'
import { Route as ApplicantPersonalInfoRouteImport } from './routes/_applicant/personal-info'
import { Route as ApplicantProgrammesRouteImport } from './routes/_applicant/programmes'
import { Route as ApplicantStudyPlanRouteImport } from './routes/_applicant/study-plan'
import { Route as ApplicantSubmitApplicationRouteImport } from './routes/_applicant/submit-application'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OfficerIndexRouteImport } from './routes/officer/index'
import { Route as AdminProgrammesIndexRouteImport } from './routes/admin/programmes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as OfficerApplicationsIndexRouteImport } from './routes/officer/applications/index'
import { Route as OfficerApplicationsRefRouteImport } from './routes/officer/applications/$ref'
import { Route as OfficerNotificationsIndexRouteImport } from './routes/officer/notifications/index'
import { Route as OfficerSelectionIndexRouteImport } from './routes/officer/selection/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantRouteRoute = ApplicantRouteRouteImport.update({
  id: '/_applicant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRouteRoute = OfficerRouteRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantCoursesRoute = ApplicantCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantDashboardRoute = ApplicantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantEducationRoute = ApplicantEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantPaymentsRoute = ApplicantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantPersonalInfoRoute = ApplicantPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantProgrammesRoute = ApplicantProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantStudyPlanRoute = ApplicantStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => ApplicantRouteRoute,
} as any)
const ApplicantSubmitApplicationRoute =
  ApplicantSubmitApplicationRouteImport.update({
    id: '/submit-application',
    path: '/submit-application',
    getParentRoute: () => ApplicantRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRouteRoute,
} as any)
const AdminProgrammesIndexRoute = AdminProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OfficerApplicationsIndexRoute =
  OfficerApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => OfficerRouteRoute,
  } as any)
const OfficerApplicationsRefRoute = OfficerApplicationsRefRouteImport.update({
  id: '/applications/$ref',
  path: '/applications/$ref',
  getParentRoute: () => OfficerRouteRoute,
} as any)
const OfficerNotificationsIndexRoute =
  OfficerNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => OfficerRouteRoute,
  } as any)
const OfficerSelectionIndexRoute = OfficerSelectionIndexRouteImport.update({
  id: '/selection/',
  path: '/selection/',
  getParentRoute: () => OfficerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/officer': typeof OfficerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/courses': typeof ApplicantCoursesRoute
  '/dashboard': typeof ApplicantDashboardRoute
  '/education': typeof ApplicantEducationRoute
  '/payments': typeof ApplicantPaymentsRoute
  '/personal-info': typeof ApplicantPersonalInfoRoute
  '/programmes': typeof ApplicantProgrammesRoute
  '/study-plan': typeof ApplicantStudyPlanRoute
  '/submit-application': typeof ApplicantSubmitApplicationRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/applications/$ref': typeof OfficerApplicationsRefRoute
  '/admin/programmes/': typeof AdminProgrammesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/officer/applications/': typeof OfficerApplicationsIndexRoute
  '/officer/notifications/': typeof OfficerNotificationsIndexRoute
  '/officer/selection/': typeof OfficerSelectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/courses': typeof ApplicantCoursesRoute
  '/dashboard': typeof ApplicantDashboardRoute
  '/education': typeof ApplicantEducationRoute
  '/payments': typeof ApplicantPaymentsRoute
  '/personal-info': typeof ApplicantPersonalInfoRoute
  '/programmes': typeof ApplicantProgrammesRoute
  '/study-plan': typeof ApplicantStudyPlanRoute
  '/submit-application': typeof ApplicantSubmitApplicationRoute
  '/admin': typeof AdminIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/officer/applications/$ref': typeof OfficerApplicationsRefRoute
  '/admin/programmes': typeof AdminProgrammesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/officer/applications': typeof OfficerApplicationsIndexRoute
  '/officer/notifications': typeof OfficerNotificationsIndexRoute
  '/officer/selection': typeof OfficerSelectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_applicant': typeof ApplicantRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/officer': typeof OfficerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/_applicant/courses': typeof ApplicantCoursesRoute
  '/_applicant/dashboard': typeof ApplicantDashboardRoute
  '/_applicant/education': typeof ApplicantEducationRoute
  '/_applicant/payments': typeof ApplicantPaymentsRoute
  '/_applicant/personal-info': typeof ApplicantPersonalInfoRoute
  '/_applicant/programmes': typeof ApplicantProgrammesRoute
  '/_applicant/study-plan': typeof ApplicantStudyPlanRoute
  '/_applicant/submit-application': typeof ApplicantSubmitApplicationRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/applications/$ref': typeof OfficerApplicationsRefRoute
  '/admin/programmes/': typeof AdminProgrammesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/officer/applications/': typeof OfficerApplicationsIndexRoute
  '/officer/notifications/': typeof OfficerNotificationsIndexRoute
  '/officer/selection/': typeof OfficerSelectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/officer'
    | '/login'
    | '/registration'
    | '/courses'
    | '/dashboard'
    | '/education'
    | '/payments'
    | '/personal-info'
    | '/programmes'
    | '/study-plan'
    | '/submit-application'
    | '/admin/'
    | '/officer/'
    | '/officer/applications/$ref'
    | '/admin/programmes/'
    | '/admin/users/'
    | '/officer/applications/'
    | '/officer/notifications/'
    | '/officer/selection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registration'
    | '/courses'
    | '/dashboard'
    | '/education'
    | '/payments'
    | '/personal-info'
    | '/programmes'
    | '/study-plan'
    | '/submit-application'
    | '/admin'
    | '/officer'
    | '/officer/applications/$ref'
    | '/admin/programmes'
    | '/admin/users'
    | '/officer/applications'
    | '/officer/notifications'
    | '/officer/selection'
  id:
    | '__root__'
    | '/'
    | '/_applicant'
    | '/admin'
    | '/officer'
    | '/login'
    | '/registration'
    | '/_applicant/courses'
    | '/_applicant/dashboard'
    | '/_applicant/education'
    | '/_applicant/payments'
    | '/_applicant/personal-info'
    | '/_applicant/programmes'
    | '/_applicant/study-plan'
    | '/_applicant/submit-application'
    | '/admin/'
    | '/officer/'
    | '/officer/applications/$ref'
    | '/admin/programmes/'
    | '/admin/users/'
    | '/officer/applications/'
    | '/officer/notifications/'
    | '/officer/selection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicantRouteRoute: typeof ApplicantRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OfficerRouteRoute: typeof OfficerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_applicant': {
      id: '/_applicant'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ApplicantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_applicant/courses': {
      id: '/_applicant/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ApplicantCoursesRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/dashboard': {
      id: '/_applicant/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ApplicantDashboardRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/education': {
      id: '/_applicant/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof ApplicantEducationRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/payments': {
      id: '/_applicant/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ApplicantPaymentsRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/personal-info': {
      id: '/_applicant/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof ApplicantPersonalInfoRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/programmes': {
      id: '/_applicant/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ApplicantProgrammesRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/study-plan': {
      id: '/_applicant/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof ApplicantStudyPlanRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/_applicant/submit-application': {
      id: '/_applicant/submit-application'
      path: '/submit-application'
      fullPath: '/submit-application'
      preLoaderRoute: typeof ApplicantSubmitApplicationRouteImport
      parentRoute: typeof ApplicantRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
    '/admin/programmes/': {
      id: '/admin/programmes/'
      path: '/programmes'
      fullPath: '/admin/programmes/'
      preLoaderRoute: typeof AdminProgrammesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/officer/applications/': {
      id: '/officer/applications/'
      path: '/applications'
      fullPath: '/officer/applications/'
      preLoaderRoute: typeof OfficerApplicationsIndexRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
    '/officer/applications/$ref': {
      id: '/officer/applications/$ref'
      path: '/applications/$ref'
      fullPath: '/officer/applications/$ref'
      preLoaderRoute: typeof OfficerApplicationsRefRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
    '/officer/notifications/': {
      id: '/officer/notifications/'
      path: '/notifications'
      fullPath: '/officer/notifications/'
      preLoaderRoute: typeof OfficerNotificationsIndexRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
    '/officer/selection/': {
      id: '/officer/selection/'
      path: '/selection'
      fullPath: '/officer/selection/'
      preLoaderRoute: typeof OfficerSelectionIndexRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
  }
}

interface ApplicantRouteRouteChildren {
  ApplicantCoursesRoute: typeof ApplicantCoursesRoute
  ApplicantDashboardRoute: typeof ApplicantDashboardRoute
  ApplicantEducationRoute: typeof ApplicantEducationRoute
  ApplicantPaymentsRoute: typeof ApplicantPaymentsRoute
  ApplicantPersonalInfoRoute: typeof ApplicantPersonalInfoRoute
  ApplicantProgrammesRoute: typeof ApplicantProgrammesRoute
  ApplicantStudyPlanRoute: typeof ApplicantStudyPlanRoute
  ApplicantSubmitApplicationRoute: typeof ApplicantSubmitApplicationRoute
}

const ApplicantRouteRouteChildren: ApplicantRouteRouteChildren = {
  ApplicantCoursesRoute: ApplicantCoursesRoute,
  ApplicantDashboardRoute: ApplicantDashboardRoute,
  ApplicantEducationRoute: ApplicantEducationRoute,
  ApplicantPaymentsRoute: ApplicantPaymentsRoute,
  ApplicantPersonalInfoRoute: ApplicantPersonalInfoRoute,
  ApplicantProgrammesRoute: ApplicantProgrammesRoute,
  ApplicantStudyPlanRoute: ApplicantStudyPlanRoute,
  ApplicantSubmitApplicationRoute: ApplicantSubmitApplicationRoute,
}

const ApplicantRouteRouteWithChildren = ApplicantRouteRoute._addFileChildren(
  ApplicantRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProgrammesIndexRoute: typeof AdminProgrammesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminProgrammesIndexRoute: AdminProgrammesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OfficerRouteRouteChildren {
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerApplicationsRefRoute: typeof OfficerApplicationsRefRoute
  OfficerApplicationsIndexRoute: typeof OfficerApplicationsIndexRoute
  OfficerNotificationsIndexRoute: typeof OfficerNotificationsIndexRoute
  OfficerSelectionIndexRoute: typeof OfficerSelectionIndexRoute
}

const OfficerRouteRouteChildren: OfficerRouteRouteChildren = {
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerApplicationsRefRoute: OfficerApplicationsRefRoute,
  OfficerApplicationsIndexRoute: OfficerApplicationsIndexRoute,
  OfficerNotificationsIndexRoute: OfficerNotificationsIndexRoute,
  OfficerSelectionIndexRoute: OfficerSelectionIndexRoute,
}

const OfficerRouteRouteWithChildren = OfficerRouteRoute._addFileChildren(
  OfficerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicantRouteRoute: ApplicantRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OfficerRouteRoute: OfficerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
